@startuml

skinparam backgroundColor white
skinparam shadowing false
skinparam defaultFontName Arial
skinparam defaultFontSize 18
skinparam dpi 150
skinparam maxMessageSize 90

skinparam sequence {
    ArrowColor black
    LifeLineBorderColor #444444
    LifeLineBackgroundColor white
    ParticipantBorderColor #444444
    ParticipantBackgroundColor white
    ParticipantFontColor black
    GroupBorderColor #444444
    GroupBackgroundColor #F7F7F7
    DividerBorderColor #444444
    DividerBackgroundColor #F2F2F2
}

<style>
sequenceDiagram {
  participant {
    Padding 20
  }
  group {
    Padding 10
    BackgroundColor #F7F7F7
    LineColor #444444
  }
  lifeLine {
    LineColor #444444
    BackgroundColor white
  }
  arrow {
    LineColor black
  }
}
</style>

hide footbox
hide footbox
autonumber

participant "p:PassengerClient" as P
participant "api:APIGateway" as API
participant "rrm:RideRequestManager" as RRM
participant "esg:ExternalServicesGateway" as ESG
participant "fm:FleetMonitor" as FM
participant "pm:PersistenceManager" as PM

activate P

P -> API: cancelRideRequest(requestId)
activate API

API -> RRM: cancel(requestId, passengerId)
activate RRM

RRM -> PM: findRequest(requestId)
activate PM
PM --> RRM: request or none
deactivate PM

opt request has an assigned robotaxi

    RRM -> FM: getFleetStatus()
    activate FM
    FM --> RRM: currentFleetStatus
    deactivate FM

end

alt cancellation allowed

    opt request has an assigned robotaxi

        RRM -> ESG: commandRoute(robotaxiId,\nnull)
        activate ESG
        ESG --> RRM: routeRevoked
        deactivate ESG

        RRM -> FM: releaseAssignment(robotaxiId)
        activate FM
        FM --> RRM: assignmentReleased
        deactivate FM

    end

    RRM -> PM: releaseReservation(requestId)
    activate PM
    PM --> RRM: reservationReleased
    deactivate PM

    opt advance booking exists

        RRM -> PM: closeBooking(requestId)
        activate PM
        PM --> RRM: bookingClosed
        deactivate PM

    end

    RRM -> PM: updateStatus(requestId,\nCANCELLED)
    activate PM
    PM --> RRM: statusUpdated
    deactivate PM

    RRM --> API: cancellationConfirmed
    API --> P: cancellationConfirmation

else cancellation not allowed

    RRM --> API: cancellationRejected
    API --> P: cancellationError

end

deactivate RRM
deactivate API
deactivate P


@enduml