@startuml

skinparam backgroundColor white
skinparam shadowing false
skinparam defaultFontName Arial
skinparam defaultFontSize 18
skinparam dpi 150
skinparam maxMessageSize 90

skinparam sequence {
    ArrowColor black
    LifeLineBorderColor #444444
    LifeLineBackgroundColor white
    ParticipantBorderColor #444444
    ParticipantBackgroundColor white
    ParticipantFontColor black
    GroupBorderColor #444444
    GroupBackgroundColor #F7F7F7
    DividerBorderColor #444444
    DividerBackgroundColor #F2F2F2
}

<style>
sequenceDiagram {
  participant {
    Padding 20
  }
  group {
    Padding 10
    BackgroundColor #F7F7F7
    LineColor #444444
  }
  lifeLine {
    LineColor #444444
    BackgroundColor white
  }
  arrow {
    LineColor black
  }
}
</style>

hide footbox
autonumber

participant "p:PassengerClient" as P
participant "api:APIGateway" as API
participant "rrm:RideRequestManager" as RRM
participant "pm:PersistenceManager" as PM
participant "fm:FleetMonitor" as FM
participant "am:AllocationManager" as AM
participant "esg:ExternalServicesGateway" as ESG

activate P

P -> API: submitImmediateRide(pickup,\ndestination)
activate API

API -> RRM: submitImmediate(passengerId,\npickup, destination)
activate RRM

RRM -> PM: create(request)
activate PM
PM --> RRM: rideRequest
deactivate PM

RRM -> ESG: getETA(pickup,\ndestination)
activate ESG
ESG --> RRM: estimatedRideTime
deactivate ESG

RRM -> FM: getCandidates()
activate FM
FM --> RRM: candidates
deactivate FM

RRM -> AM: allocate(request,\ncandidates)
activate AM

opt active strategy requires ETA

    AM -> ESG: getETA(candidates,\npickup)
    activate ESG
    ESG --> AM: etaList
    deactivate ESG

end

AM --> RRM: selectedRobotaxi
deactivate AM

alt feasible robotaxi found

    RRM -> ESG: getETA(selectedRobotaxi,\npickup)
    activate ESG
    ESG --> RRM: pickupETA
    deactivate ESG

    RRM -> PM: reserve(request,\nselectedRobotaxi, timeWindow)
    activate PM
    PM --> RRM: reservationConfirmed
    deactivate PM

    RRM -> FM: assign(selectedRobotaxi,\nrequest)
    activate FM
    FM --> RRM: assignmentConfirmed
    deactivate FM

    RRM -> PM: updateStatus(request,\nACCEPTED)
    activate PM
    PM --> RRM: statusUpdated
    deactivate PM

    RRM --> API: rideRequestAccepted
    API --> P: rideConfirmation

else no feasible robotaxi

    RRM -> PM: updateStatus(request,\nREJECTED)
    activate PM
    PM --> RRM: statusUpdated
    deactivate PM

    RRM --> API: rideRequestRejected
    API --> P: rideRejection

end

deactivate RRM
deactivate API
deactivate P

@enduml
